### ISSUE TITLE
Naming convention for solutions

### ISSUE THREAD

**Issue by jrgz** [jrgz/Beginner-Projects#17]
I think we should create a naming convention and standard for solutions. There are already multiple solutions for certain projects and, for the sake of organization, a naming standard may prove to be convenient.

It was originally my intention for there to be a single, "standard" solution for each project, but I think we are going in a different direction. The README should be updated to reflect this.

What do you guys think about this?

**Comment by rsz** [comment]
How about number or author's name with it

**Comment by jrgz** [comment]
At first I thought we should do something like `projectName-authorName.py` or `projectNumber-authorName.py`or something like that, but that has the potential to create a massive list of project files per directory, which may be ultimately unproductive.

I am considering adding a README in each solution folder, in which contributors will simply add a link to their solution which will reside in their own repository, instead of having them push the raw solution files into this repository. So everyone will have to fork this repo, add their solutions to their own fork, add a link to that solution in the respective project's directory's README, and commit and push only the README to this main repo.

**Comment by jrgz** [comment]
Okay I completely implemented that change. Please tell me what you think.
